---
#- name: Pull redis image
#  shell: docker pull "{{ redis_docker_image }}:{{ redis_version }}"
#  register: result_docker
#  changed_when: False
#  until: result_docker|success
#  retries: 3
#  delay: 1
#  tags: update

- name: Start redis containers
  docker_container:
    name: redis
    image: "{{ redis_docker_image }}:{{ redis_version }}"
    network_mode: host
    state: started
    log_driver: json-file
    log_options:
      max-file: "1"
      max-size: "20m"
    labels: "{{ redis_docker_labels }}"
    restart_policy: unless-stopped
    restart_retries: 3
    volumes:
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime

- name: Create init-script rhel6
  copy: src=redis_rhel6 dest=/etc/init.d/redis owner=root group=root mode=0755
  when:
    ansible_distribution_major_version|int < 7
    and ansible_os_family == 'RedHat'

- name: Create init-script rhel7
  copy: src=redis_rhel7 dest=/usr/lib/systemd/system/redis.service owner=root group=root mode=0644
  when:
    ansible_distribution_major_version|int > 6
    and ansible_os_family == 'RedHat'

- name: Enable init-scripts
  service: name=redis enabled=yes state=started
